---
redirects:
  api: ./ref/python/public-api/README.md
  api/overview: ./library/public-api-guide.md
  api/project: ./ref/python/public-api/project.md
  api/run: ./ref/python/public-api/README.md
  cli/overview: ./ref/cli/README.md
  cli/restoring: ./ref/cli/wandb-restore.md
  docs/: ./README.md
  docs/getting-started: ./quickstart.md
  getting-started: ./quickstart.md
  huggingface: ./integrations/huggingface.md
  java: ./ref/java/README.md
  java/wandbrun-builder: ./ref/java/wandbrun-builder.md
  java/wandbrun: ./ref/java/wandbrun.md
  library/advanced: ./library/README.md
  library/advanced/grouping: ./library/grouping.md
  library/advanced/resuming: ./library/resuming.md
  library/advanced/security: ./library/security.md
  library/advanced/limits: ./library/limits.md
  library/reference: ./ref/README.md
  library/reference/wandb_api: ./ref/public-api/api.md
  library/reference/keras: ./ref/keras.md
  library/reference/data_types: ./ref/python/data-types/README.md
  library/reference/fastai: ./integrations/fastai/README.md
  library/sweeps: ./sweeps/README.md
  library/sweeps/configuration: ./sweeps/configuration.md
  library/sweeps/advanced: ./sweeps/ray-tune.md
  library/sweeps/local-controller: ./sweeps/local-controller.md
  library/sweeps/python-api: ./sweeps/python-api.md
  library/example-projects: ./examples.md
  overview/overview: ./overview.md
  sweeps/local: ./sweeps/local-controller.md
  sweeps/python: ./sweeps/python-api.md
  wandb/config: ./ref/python/config.md
  wandb/init: ./ref/python/init.md
  wandb/log: ./ref/python/log.md
  wandb/restore: ./ref/python/restore.md
  wandb/save: ./ref/python/save.md
  integrations/api: ./ref/python/public-api/README.md
  library/api: ./library/public-api-guide.md
  sweeps/overview: ./sweeps/README.md
  ref/config: ./ref/python/config.md
  library/integrations/pytorch: ./integrations/pytorch.md
  library/integrations/pytorch/lightning: ./integrations/.md
  library/integrations/keras: ./integrations/keras.md
  library/integrations/tensorflow: ./integrations/tensorflow.md
  library/integrations/scikit: ./integrations/scikit.md
  library/integrations/fastai: ./integrations/fastai/README.md
  library/integrations/fastai/fastai: ./integrations/fastai/v1.md
  library/integrations/xgboost: ./integrations/xgboost.md
  library/integrations/lightgbm: ./integrations/lightgbm.md
  library/integrations/huggingface: ./integrations/huggingface.md
  library/integrations/tensorboard: ./integrations/tensorboard.md
  library/integrations/sagemaker: ./integrations/sagemaker.md
  library/integrations/lightning: ./integrations/lightning.md
  library/integrations/ignite: ./integrations/ignite.md
  library/integrations/kubeflow: ./integrations/kubeflow.md
  library/integrations/docker: ./integrations/docker.md
  library/integrations/jupyter: ./integrations/jupyter.md
  library/integrations/databricks: ./integrations/databricks.md
  library/integrations/ray-tune: ./integrations/ray-tune.md
  library/integrations/catalyst: ./integrations/catalyst.md
  library/integrations/skorch: ./integrations/skorch.md
  library/integrations/simpletransformers: ./integrations/simpletransformers.md
  library/integrations/openai-gym: ./integrations/openai-gym.md
  library/integrations/numpy: ./integrations/numpy.md
  library/integrations/jax: ./integrations/jax.md
  library/frameworks: ./integrations/README.md
  library/frameworks/fastai: ./integrations/fastai/README.md
  library/frameworks/fastai-example: ./integrations/fastai/README.md
  library/frameworks/jax-example: ./library/example-projects/jax.md
  library/frameworks/keras: ./integrations/keras.md
  library/frameworks/numpy-example: ./library/example-projects/numpy.md
  library/frameworks/pytorch: ./integrations/pytorch.md
  library/frameworks/scikit: ./integrations/scikit.md
  library/frameworks/tensorflow: ./integrations/tensorflow.md
  library/frameworks/xgboost: ./integrations/xgboost.md
  frameworks/catalyst: ./integrations/catalyst.md
  frameworks/examples: ./examples.md
  frameworks/fastai: ./integrations/fastai/README.md
  frameworks/fastai-example: ./integrations/fastai/README.md
  frameworks/keras: ./integrations/keras.md
  frameworks/keras-example: ./integrations/keras.md
  frameworks/pytorch: ./integrations/pytorch.md
  frameworks/pytorch-example: ./integrations/pytorch.md
  frameworks/scikit: ./integrations/scikit.md
  frameworks/scikit-example: ./integrations/scikit.md
  frameworks/tensorflow: ./integrations/tensorflow.md
  frameworks/tensorflow-example: ./integrations/tensorflow.md
  frameworks/xgboost: ./integrations/xgboost.md
  frameworks/xgboost-example: ./integrations/xgboost.md
  ref/export-api: ./library/public-api-guide.md
  ref/export-api/api: ./ref/public-api/README.md
  ref/export-api/examples: ./library/public-api-guide.md
  ref/artifact: ./ref/python/artifact.md
  ref/run: ./ref/python/run.md
  ref/run/alert: ./ref/python/run.md
  ref/run/config: ./ref/python/config.md
  ref/run/init: ./ref/python/init.md
  ref/run/log: ./ref/python/log.md
  ref/run/login: ./ref/python/login.md
  ref/run/summary: ./ref/python/summary.md
  ref/data-types: ./ref/python/data-types/README.md
  ref/data-types/audio: ./ref/python/data-types/audio.md
  ref/data-types/histogram: ./ref/python/data-types/histogram.md
  ref/data-types/html: ./ref/python/data-types/html.md
  ref/data-types/image: ./ref/python/data-types/image.md
  ref/data-types/molecule: ./ref/python/data-types/molecule.md
  ref/data-types/object3d: ./ref/python/data-types/object3d.md
  ref/data-types/plotly: ./ref/python/data-types/plotly.md
  ref/data-types/table: ./ref/python/data-types/table.md
  ref/data-types/video: ./ref/python/data-types/video.md
  ref/cli: ./ref/cli/README.md
  alerts/slack: ./ref/app/features/alerts.md
  app/pages: ./ref/app/pages/README.md
  app/pages/project-page: ./ref/app/pages/project-page.md
  app/pages/workspaces: ./ref/app/pages/workspaces.md
  app/pages/run-page: ./ref/app/pages/run-page.md
  app/features: ./ref/app/features/README.md
  app/features/anon: ./ref/app/features/anon.md
  app/features/custom-charts: ./ref/app/features/custom-charts/README.md
  app/features/custom-charts/walkthrough: ./ref/app/features/custom-charts/walkthrough.md
  app/features/sidebar: ./ref/app/features/runs-table.md
  app/features/tags: ./ref/app/features/tags.md
  app/features/notes: ./ref/app/features/notes.md
  app/features/sweeps: ./ref/app/features/sweeps.md
  app/features/alerts: ./ref/app/features/alerts.md
  app/features/teams: ./ref/app/features/teams.md
  app/features/system-metrics: ./ref/app/features/system-metrics.md
  app/features/panels: ./ref/app/features/panels/README.md
  app/features/panels/code: ./ref/app/features/panels/code.md
  app/features/panels/parallel-coordinates: ./ref/app/features/panels/parallel-coordinates.md
  app/features/panels/compare-metrics: ./ref/app/features/panels/line-plot/README.md
  app/features/panels/compare-metrics/reference: ./ref/app/features/panels/line-plot/reference.md
  app/features/panels/compare-metrics/sampling-and-bucketing: ./ref/app/features/panels/line-plot/sampling.md
  app/features/panels/compare-metrics/smoothing: ./ref/app/features/panels/line-plot/smoothing.md
  app/features/panels/parameter-importance: ./ref/app/features/panels/parameter-importance.md
  app/features/panels/run-colors: ./ref/app/features/panels/run-colors.md
  app/features/panels/run-comparer: ./ref/app/features/panels/run-comparer.md
  app/features/panels/scatter-plot: ./ref/app/features/panels/scatter-plot.md
  
