---
redirects:
  alerts/slack: ./app/features/alerts.md
  api: ./ref/python/public-api/README.md
  api/overview: ./library/public-api-guide.md
  api/project: ./ref/python/public-api/project.md
  api/run: ./ref/python/public-api/README.md
  cli/overview: ./ref/cli/README.md
  cli/restoring: ./ref/cli/wandb-restore.md
  docs/: ./README.md
  docs/getting-started: ./quickstart.md
  getting-started: ./quickstart.md
  huggingface: ./integrations/huggingface.md
  java: ./ref/java/README.md
  java/wandbrun-builder: ./ref/java/wandbrun-builder.md
  java/wandbrun: ./ref/java/wandbrun.md
  library/advanced: ./library/README.md
  library/advanced/grouping: ./library/grouping.md
  library/advanced/resuming: ./library/resuming.md
  library/advanced/security: ./library/security.md
  library/advanced/limits: ./library/limits.md
  library/reference: ./ref/README.md
  library/reference/wandb_api: ./ref/public-api/api.md
  library/reference/keras: ./ref/keras.md
  library/reference/data_types: ./ref/python/data-types/README.md
  library/reference/fastai: ./integrations/fastai/README.md
  library/sweeps: ./sweeps/README.md
  library/sweeps/configuration: ./sweeps/configuration.md
  library/sweeps/advanced: ./sweeps/ray-tune.md
  library/sweeps/local-controller: ./sweeps/local-controller.md
  library/sweeps/python-api: ./sweeps/python-api.md
  library/example-projects: ./examples.md
  overview/overview: ./overview.md
  sweeps/local: ./sweeps/local-controller.md
  sweeps/python: ./sweeps/python-api.md
  wandb/config: ./ref/python/config.md
  wandb/init: ./ref/python/init.md
  wandb/log: ./ref/python/log.md
  wandb/restore: ./ref/python/restore.md
  wandb/save: ./ref/python/save.md
  integrations/api: ./ref/python/public-api/README.md
  library/api: ./library/public-api-guide.md
  sweeps/overview: ./sweeps/README.md
  ref/config: ./ref/python/config.md
  library/integrations/pytorch: ./integrations/pytorch.md
  library/integrations/pytorch/lightning: ./integrations/.md
  library/integrations/keras: ./integrations/keras.md
  library/integrations/tensorflow: ./integrations/tensorflow.md
  library/integrations/scikit: ./integrations/scikit.md
  library/integrations/fastai: ./integrations/fastai/README.md
  library/integrations/fastai/fastai: ./integrations/fastai/v1.md
  library/integrations/xgboost: ./integrations/xgboost.md
  library/integrations/lightgbm: ./integrations/lightgbm.md
  library/integrations/huggingface: ./integrations/huggingface.md
  library/integrations/tensorboard: ./integrations/tensorboard.md
  library/integrations/sagemaker: ./integrations/sagemaker.md
  library/integrations/lightning: ./integrations/lightning.md
  library/integrations/ignite: ./integrations/ignite.md
  library/integrations/kubeflow: ./integrations/kubeflow.md
  library/integrations/docker: ./integrations/docker.md
  library/integrations/jupyter: ./integrations/jupyter.md
  library/integrations/databricks: ./integrations/databricks.md
  library/integrations/ray-tune: ./integrations/ray-tune.md
  library/integrations/catalyst: ./integrations/catalyst.md
  library/integrations/skorch: ./integrations/skorch.md
  library/integrations/simpletransformers: ./integrations/simpletransformers.md
  library/integrations/openai-gym: ./integrations/openai-gym.md
  library/integrations/numpy: ./integrations/numpy.md
  library/integrations/jax: ./integrations/jax.md
  library/frameworks: ./integrations/README.md
  library/frameworks/fastai: ./integrations/fastai/README.md
  library/frameworks/fastai-example: ./integrations/fastai/README.md
  library/frameworks/jax-example: ./library/example-projects/jax.md
  library/frameworks/keras: ./integrations/keras.md
  library/frameworks/numpy-example: ./library/example-projects/numpy.md
  library/frameworks/pytorch: ./integrations/pytorch.md
  library/frameworks/scikit: ./integrations/scikit.md
  library/frameworks/tensorflow: ./integrations/tensorflow.md
  library/frameworks/xgboost: ./integrations/xgboost.md
  frameworks/catalyst: ./integrations/catalyst.md
  frameworks/examples: ./examples.md
  frameworks/fastai: ./integrations/fastai/README.md
  frameworks/fastai-example: ./integrations/fastai/README.md
  frameworks/keras: ./integrations/keras.md
  frameworks/keras-example: ./integrations/keras.md
  frameworks/pytorch: ./integrations/pytorch.md
  frameworks/pytorch-example: ./integrations/pytorch.md
  frameworks/scikit: ./integrations/scikit.md
  frameworks/scikit-example: ./integrations/scikit.md
  frameworks/tensorflow: ./integrations/tensorflow.md
  frameworks/tensorflow-example: ./integrations/tensorflow.md
  frameworks/xgboost: ./integrations/xgboost.md
  frameworks/xgboost-example: ./integrations/xgboost.md
  ref/export-api: ./library/public-api-guide.md
  ref/export-api/api: ./ref/public-api/README.md
  ref/export-api/examples: ./library/public-api-guide.md
  ref/artifact: ./ref/python/artifact.md
  ref/run: ./ref/python/run.md
  ref/run/alert: ./ref/python/run.md#alert
  ref/run/config: ./ref/python/config.md
  ref/run/init: ./ref/python/init.md
  ref/run/log: ./ref/python/log.md
  ref/run/login: ./ref/python/login.md
  ref/run/summary: ./ref/python/summary.md
